spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URL}
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
          default-label: master
          clone-on-start: true
          skip-ssl-validation: true
          force-pull: true
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      discovery:
        prefer-ip-address: true
  profiles:
    active: git
server:
  port: 8888