spring:
  config:
    import: "configserver:"

  application:
    name: account

  cloud:
    config:
      uri: ${CONFIG_URL}
      fail-fast: true

logging:
  level:
    org.springframework.cloud.vault: DEBUG
    org.springframework.cloud.config: DEBUG
    org.springframework.boot.env: DEBUG