apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-theme-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistence.theme.hostPath }}
