apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.env.KEYCLOAK_ADMIN | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.env.KEYCLOAK_ADMIN_PASSWORD | quote }}
  POSTGRES_USER: {{ .Values.env.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.env.POSTGRES_PASSWORD | quote }}