apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: {{ .Values.service.type }}
  selector:
    app: keycloak
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
    - name: debug
      port: {{ .Values.service.debugPort }}
      targetPort: 5005