openapi: 3.0.3
info:
  title: Notification API
  version: 1.0.0
  description: API для отправки email-уведомлений

servers:
  - url: http://localhost:8080/api/notification

security:
  - bearerAuth: [ ]

paths:
  /mail:
    post:
      summary: Отправка email-сообщения
      operationId: sendMail
      tags:
        - notification
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MailDto'
      responses:
        '200':
          description: Сообщение успешно отправлено

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    MailDto:
      type: object
      required:
        - email
        - subject
        - text
      properties:
        email:
          type: string
          format: email
          example: "user@example.com"
          description: Email получателя
        subject:
          type: string
          example: "Уведомление о платеже"
          description: Тема письма
        text:
          type: string
          example: "Ваш перевод успешно выполнен."
          description: Текст письма