/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.yandex.practicum.bank.client.transfer.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseStatus;
import ru.yandex.practicum.bank.client.transfer.model.TransferDto;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-06-14T20:54:57.348613+03:00[Europe/Moscow]", comments = "Generator version: 7.12.0")
@Validated
@Tag(name = "transfer", description = "the transfer API")
public interface TransferApi {

    /**
     * POST / : Перевод средств между счетами
     *
     * @param transferDto  (required)
     * @return Перевод успешно выполнен (status code 200)
     */
    @Operation(
        operationId = "transfer",
        summary = "Перевод средств между счетами",
        tags = { "transfer" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Перевод успешно выполнен")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/",
        consumes = "application/json"
    )
    @ResponseStatus(HttpStatus.OK)
    
    void transfer(
        @Parameter(name = "TransferDto", description = "", required = true) @Valid @RequestBody TransferDto transferDto
    );

}
