apiVersion: v1
kind: Secret
metadata:
  name: exchange-generator-secret
type: Opaque
stringData:
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_EXCHANGE_GENERATOR_CLIENT_ID: {{ .Values.secrets.oauth2.clientId | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION__EXCHANGE_GENERATOR_CLIENT_SECRET: {{ .Values.secrets.oauth2.secret | quote }}