apiVersion: v1
kind: Service
metadata:
  name: exchange-generator
spec:
  selector:
    app: exchange-generator
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}