/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.yandex.practicum.bank.client.cash.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseStatus;
import ru.yandex.practicum.bank.client.cash.model.CashTransactionDto;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-06-13T23:13:29.470866+03:00[Europe/Moscow]", comments = "Generator version: 7.12.0")
@Validated
@Tag(name = "Cash", description = "the Cash API")
public interface CashApi {

    /**
     * PUT /put : Пополнение счёта
     *
     * @param cashTransactionDto  (required)
     * @return Средства успешно зачислены (status code 200)
     */
    @Operation(
        operationId = "putCash",
        summary = "Пополнение счёта",
        tags = { "Cash" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Средства успешно зачислены")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/put",
        consumes = "application/json"
    )
    @ResponseStatus(HttpStatus.OK)
    
    void putCash(
        @Parameter(name = "CashTransactionDto", description = "", required = true) @Valid @RequestBody CashTransactionDto cashTransactionDto
    );


    /**
     * PUT /withdraw : Снятие со счёта
     *
     * @param cashTransactionDto  (required)
     * @return Средства успешно списаны (status code 200)
     */
    @Operation(
        operationId = "withdrawCash",
        summary = "Снятие со счёта",
        tags = { "Cash" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Средства успешно списаны")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/withdraw",
        consumes = "application/json"
    )
    @ResponseStatus(HttpStatus.OK)
    
    void withdrawCash(
        @Parameter(name = "CashTransactionDto", description = "", required = true) @Valid @RequestBody CashTransactionDto cashTransactionDto
    );

}
