apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-practicum-bank-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://practicum-bank"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE, PATCH"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type, Set-Cookie"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: practicum-bank
      http:
        paths:
          - path: /api/account(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: account
                port:
                  number: 8082
          - path: /api/exchange(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: exchange
                port:
                  number: 8084
          - path: /api/cash(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: cash
                port:
                  number: 8083
          - path: /api/notification(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: notification
                port:
                  number: 8088
          - path: /api/transfer(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: transfer
                port:
                  number: 8086
          - path: /api/blocker(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: blocker
                port:
                  number: 8087
