
apiVersion: v1
kind: Service
metadata:
  name: practicum-bank
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: ingress-nginx-controller.ingress-nginx.svc.cluster.local