apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: practicum-bank-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://practicum-bank"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE, PATCH"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type, Set-Cookie"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  rules:
    - host: practicum-bank
      http:
        paths:
          - path: /realms
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080

          - path: /login/oauth2/code
            pathType: Prefix
            backend:
              service:
                name: front-ui
                port:
                  number: 8081

          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080

          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-ui
                port:
                  number: 8081

          - path: /account
            pathType: Prefix
            backend:
              service:
                name: front-ui
                port:
                  number: 8081

          - path: /cash
            pathType: Prefix
            backend:
              service:
                name: front-ui
                port:
                  number: 8081

          - path: /transfer
            pathType: Prefix
            backend:
              service:
                name: front-ui
                port:
                  number: 8081

          - path: /user
            pathType: Prefix
            backend:
              service:
                name: front-ui
                port:
                  number: 8081

          - path: /force-logout
            pathType: Prefix
            backend:
              service:
                name: front-ui
                port:
                  number: 8081


          - path: /api/account
            pathType: Prefix
            backend:
              service:
                name: account
                port:
                  number: 8082
