apiVersion: v1
kind: ConfigMap
metadata:
  name: front-ui-config
data:
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: {{ .Values.configMap.jwtIssuerUri | default .Values.global.jwtIssuerUri | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_REDIRECT_URL: {{ .Values.configMap.keycloakRedirectUrl | default .Values.global.keycloakRedirectUrl | quote }}
  API_ACCOUNT: {{ .Values.configMap.api.account | default .Values.global.api.account | quote }}
  API_CASH: {{ .Values.configMap.api.cash | default .Values.global.api.cash | quote }}
  API_TRANSFER: {{ .Values.configMap.api.transfer | default .Values.global.api.transfer | quote }}
  SERVER_PORT: {{ .Values.service.port | quote }}
