apiVersion: v1
kind: Secret
metadata:
  name: front-ui-secret
type: Opaque
stringData:
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID: {{ .Values.secrets.oauth2.clientId | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_SECRET: {{ .Values.secrets.oauth2.clientSecret | quote }}
  KEYCLOAK_ADMIN_SERVER_URL: {{ .Values.secrets.keycloakAdmin.serverUrl | quote }}
  KEYCLOAK_ADMIN_USERNAME: {{ .Values.secrets.keycloakAdmin.username | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.secrets.keycloakAdmin.password | quote }}
  KEYCLOAK_ADMIN_REALM: {{ .Values.secrets.keycloakAdmin.realm | quote }}