apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.secrets.db | quote }}
  POSTGRES_USER: {{ .Values.secrets.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.password | quote }}