apiVersion: v1
kind: ConfigMap
metadata:
  name: account-config
data:
  SPRING_DATASOURCE_URL: {{ .Values.configMap.datasourceUrl | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:  {{ .Values.configMap.jwtIssuerUri | default .Values.global.jwtIssuerUri | quote }}
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:  {{ .Values.configMap.zipkin | default .Values.global.zipkin | quote }}
  SERVER_PORT: {{ .Values.service.port | quote }}
  SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: {{ .Values.configMap.kafkaBootstrapServers | default .Values.global.kafkaBootstrapServers | quote}}
