apiVersion: v1
kind: Secret
metadata:
  name: account-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.password | quote }}
  SPRING_DATASOURCE_DB: {{ .Values.secrets.db | quote }}