replicaCount: 1

image:
  repository: keycloak/keycloak
  tag: "26.2.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  debugPort: 5005

env:
  KEYCLOAK_ADMIN: ""
  KEYCLOAK_ADMIN_PASSWORD: ""

  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""

postgres:
  host: "postgres"
  port: 5432
  db: "keycloak"

persistence:
  data:
    enabled: true
    size: 1Gi
    accessModes: ["ReadWriteOnce"]
  theme:
    hostPath: /Users/abramovaleksandr/PhpstormProjects/practicum-bank/keycloak-themes
